name: Deploy .NET Framework to AWS EC2

on:
  push:
    branches:
      #- master
      - main

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET Framework 4.8
        uses: microsoft/setup-msbuild@v1

      - name: Restaurar paquetes NuGet
        run: nuget restore DemoApi.sln

      - name: Publicar Web App
        run: |
          msbuild DemoApi.sln `
            /p:Configuration=Release `
            /p:Platform="Any CPU" `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:publishUrl="DemoApi\bin\Release\app.publish" `
            /p:PackageAsSingleFile=false

      - name: Configurar AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
  
      - name: Crear archivo ZIP para CodeDeploy
        run: Compress-Archive -Path DemoApi\obj\Release\Package\PackageTmp\* -DestinationPath deploy.zip
        
      - name: Transferir Deploy.zip a S3
        run: |
          aws s3 cp deploy.zip s3://demo-api-deploy/deploy.zip
       
      - name: Desplegar con CodeDeploy
        run: |
          aws deploy create-deployment `
            --application-name DemoApiApp `
            --deployment-group-name DemoApiDeploymentGroup `
            --s3-location bucket=demo-api-deploy,key=deploy.zip,bundleType=zip
